services:
  fastapi_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - celery_worker

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    container_name: celery_worker
    restart: always
    depends_on:
      - postgres_db
      - redis_broker
      - mongodb_backend
    environment:
      POSTGRES_CONFIG: '{"dbname":"tasks","user":"dbuser","password":"dbpassword","host":"postgres_db","port":"5432"}'
      CELERY_BROKER_URL: "redis://localhost:6379/0"
      CELERY_RESULT_BACKEND: "mongodb://admin:secret@mongodb:27017/celery_results"

  redis_broker:
    build:
      context: .
      dockerfile: docker/Dockerfile.broker
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb_backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: mongodb_backend
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres_db:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db

volumes:
  redis_data:
  mongo_data:
  postgres_data: