services:
  fastapi_app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb_backend
      - celery_worker
    environment:
      POSTGRES_CONFIG: '{"dbname":"tasks","user":"dbuser","password":"dbpassword","host":"postgres_db","port":"5432"}'
      CELERY_BROKER_URL: "mongodb://admin:secret@mongodb:27017/celery_broker"
      CELERY_RESULT_BACKEND: "mongodb://admin:secret@mongodb:27017/celery_results"

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    container_name: celery_worker
    restart: always
    depends_on:
      - mongodb_backend
    environment:
      POSTGRES_CONFIG: '{"dbname":"tasks","user":"dbuser","password":"dbpassword","host":"postgres_db","port":"5432"}'
      CELERY_BROKER_URL: "mongodb://admin:secret@mongodb_backend:27017/celery_broker"
      CELERY_RESULT_BACKEND: "mongodb://admin:secret@mongodb_backend:27017/celery_results"

  redis_broker:
    build:
      context: .
      dockerfile: docker/Dockerfile.broker
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb_backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.broker
    container_name: mongodb_backend
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db

  postgres_db:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db

volumes:
  redis_data:
  mongo_data:
  postgres_data: