services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - celery_worker
    environment:
      MONGO_URI: "mongodb://admin:secret@mongodb:27017"
      CELERY_BROKER_URL: "mongodb://admin:secret@mongodb:27017/celery_broker"
      CELERY_RESULT_BACKEND: "mongodb://admin:secret@mongodb:27017/celery_results"
    networks:
      - backend

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: celery_worker
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://admin:secret@mongodb:27017"
      CELERY_BROKER_URL: "mongodb://admin:secret@mongodb:27017/celery_broker"
      CELERY_RESULT_BACKEND: "mongodb://admin:secret@mongodb:27017/celery_results"
    networks:
      - backend

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
volumes:
  mongo_data:
networks:
  backend:
    driver: backend